#-*- conding:utf8 -*-

print('What do you get when you cross a snowman with a vampire?')
input()
print("Frostbite!")
print()
print('What do dentists call a atronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interruption cow wh', end='')
print('-MOO!')